namespace Roll20_Companion.Models
{
    public enum Dice
    {
        d2,
        d3,
        d4,
        d6,
        d8,
        d10,
        d12,
        d20,
        d100
    }
    public enum DamageType
    {
        Untyped,
        Slashing,
        Piercing,
        Bludgeoning,
        Force,
        Fire,
        Cold,
        Acid,
        Electricity,
        Sonic,
        PositiveEnergy,
        NegativeEnergy,
        Divine,
        Vile,
        NonLethal,
        Strength,
        Dexterity,
        Constitution,
        Intelligence,
        Wisdom,
        Charisma
    }
    public enum BonusType
    {
        Untyped,
        Morale,
        Magic,
        Sacred,
        Profane,
        Dodge,
        Deflection,
        NaturalArmor,
        Armor,
        Shield,
        ArmorEnhancement,
        ShieldEnhancement,
        NaturalArmorEnhancement,
        Size
    }
}
